class Field:
    error = 'error'
    request_ip = 'request_ip'
    client_request = 'client_request'
    writing_to_neo = 'writing_to_neo'
    ready = 'ready'
    request_id = 'request_id'
    request_type = 'request_type'
    request = 'request'
    processing = 'processing'
    failed_redis_writers = 'failed_redis_writers'
    all_redis_success = 'all_redis_success'
    finished_processing_request = 'finished_processing_request'
    redis_sizes = 'redis_sizes'
    white_list_content = 'white_list_content'
    execution_environment = 'execution_environment'
    element_type = 'element_type'
    percent_done = 'percent_done'
