# model attributes
IN = "IN"
OUT = "OUT"
DIRECTION = "direction"
ID = "id"
LABEL = "label"
UNIPOP = "unipop"
VERTICES = "vertices"
EDGES = "edges"
IDENTIFIES = "Identifies"
PROPERTIES = "properties"
FIELDS = "fields"
FIELD = "field"
DELIMITER = "delimiter"
DELIMITER_VALUE = "~"
READONLY_FIELDS = "readonlyFields"
PROPERTY_FROM_TABLE_PREFIX = "@"
INCLUDE = "include"
TYPE = "type"
PRIMITIVE_TYPE = "primitiveType"
PRIMITIVE_TYPE_FORMAT = "primitiveTypeFormat"

# logical definitions
MODEL = "model"
VERTEX = "vertex"
EDGE = "edge"
IDENTIFIER = "Identifier"

